### ISSUE TITLE
Ansible vault error when checking the passwords file

### ISSUE THREAD

**Issue by verdurin** [stackhpc/kayobe-original#186]
On a test system I see the following error:
```
TASK [kolla-ansible : Ensure the Kolla passwords file exists] **********************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "ansible-vault decrypt --vault-password-file /tmp/tmpgExNTu /tmp/tmpFwyBsD", "msg": "ERROR! input is not vault encrypted data/tmp/tmpFwyBsD is not a vault encrypted file for /tmp/tmpFwyBsD", "rc": 1, "stderr": "ERROR! input is not vault encrypted data/tmp/tmpFwyBsD is not a vault encrypted file for /tmp/tmpFwyBsD\n", "stderr_lines": ["ERROR! input is not vault encrypted data/tmp/tmpFwyBsD is not a vault encrypted file for /tmp/tmpFwyBsD"], "stdout": "", "stdout_lines": []}
```

The command-line is:
` kayobe   overcloud host configure  --vault-password-file /home/kayobe/information`

The file `etc/kolla/passwords.yml` does exist.

**Comment by markgoddard** [comment]
Hi Adam, I'm afraid the --vault-password-file argument doesn't work currently - you should use one of the other two methods ($KAYOBE_VAULT_PASSWORD or --ask-vault-pass). There is a story covering this here: https://storyboard.openstack.org/#!/story/2001664

Also, please raise issues on storyboard rather than Github.
