### ISSUE TITLE
Kayobe uses personal github repositories

### ISSUE THREAD

**Issue by autonomouse** [stackhpc/kayobe-original#49]
Kayobe uses personal github repositories (e.g https://github.com/jriguera/ansible-role-configdrive/ and 
https://github.com/ahuffman/ansible-resolv) which should be backed up on stackHPC’s own github account and/or moved to ansible galaxy (to ensure they don’t disappear overnight if their owners close their github accounts or something)

**Comment by markgoddard** [comment]
They're already on galaxy - we reference them by their galaxy name rather than via their git repo: https://github.com/stackhpc/kayobe/blob/master/ansible/requirements.yml

There is occasionally an exception or two, where we point to StackHPC's github fork until a pull request to the upstream repo has been merged. This is currently the case for the `singleplatform-eng.users` role:

```
#- src: singleplatform-eng.users
- src: https://github.com/stackhpc/ansible-users
  version: append
```

**Comment by markgoddard** [comment]
Example: https://galaxy.ansible.com/jriguera/configdrive/

**Comment by markgoddard** [comment]
Closing based on the last comment. @autonomouse please feel free to reopen this if you aren't satisfied by my response.
